import { Record } from './types';

// Enhanced mock records with additional fields and proper IDs
export const MOCK_RECORDS: Record[] = [
  {
    id: 'CAS-150123-001',
    title: 'Johnson Family Case',
    type: 'case',
    client: 'John Johnson,Mary Johnson',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-05-10'),
    status: 'active',
    tags: ['urgent', 'court-involved'],
    priority: 'high',
    completeness: 85,
    owner: 'Sarah Wilson',
    lastAccessed: new Date('2023-05-12'),
    relatedRecords: ['ASS-2023-042', 'DOC-2023-156'],
    compliance: 'complete',
    favorite: true
  },
  {
    id: 'ASS-2023-042',
    title: 'Initial Foster Carer Assessment',
    type: 'assessment',
    client: 'John Smith,Jane Smith',
    createdAt: new Date('2023-03-22'),
    updatedAt: new Date('2023-03-25'),
    status: 'pending',
    tags: ['initial', 'behavioral'],
    priority: 'medium',
    completeness: 60,
    owner: 'Michael Brown',
    lastAccessed: new Date('2023-04-10'),
    relatedRecords: ['CAS-2023-001'],
    compliance: 'incomplete'
  },
  {
    id: 'REP-2023-087',
    title: 'Monthly Placement Review',
    type: 'report',
    client: 'Sarah Williams,David Williams',
    createdAt: new Date('2023-04-30'),
    updatedAt: new Date('2023-04-30'),
    status: 'closed',
    tags: ['monthly', 'progress'],
    priority: 'low',
    completeness: 100,
    owner: 'Emily Davis',
    lastAccessed: new Date('2023-05-02'),
    compliance: 'complete'
  },
  {
    id: 'DOC-180223-156',
    title: 'CLA Review Documentation',
    type: 'document',
    client: 'James Thompson,Lisa Thompson',
    createdAt: new Date('2023-02-18'),
    updatedAt: new Date('2023-02-18'),
    status: 'active',
    tags: ['medical', 'confidential'],
    priority: 'medium',
    completeness: 100,
    owner: 'Sarah Wilson',
    relatedRecords: ['CAS-2023-001'],
    compliance: 'complete'
  },
  {
    id: 'CAS-050123-002',
    title: 'Davis Family Reunification',
    type: 'case',
    client: 'Robert Davis,Emma Davis',
    createdAt: new Date('2023-01-05'),
    updatedAt: new Date('2023-05-01'),
    status: 'active',
    tags: ['reunification', 'court-involved'],
    priority: 'urgent',
    completeness: 70,
    owner: 'Robert Johnson',
    lastAccessed: new Date('2023-05-11'),
    compliance: 'overdue',
    favorite: true
  },
  {
    id: 'DOC-100323-198',
    title: 'Risk Assessment Update',
    type: 'document',
    client: 'Michael Jones,Sophie Jones',
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-10'),
    status: 'archived',
    tags: ['education', 'school'],
    priority: 'low',
    completeness: 100,
    owner: 'Michael Brown',
    compliance: 'complete'
  },
  {
    id: 'ASS-2023-103',
    title: 'Foster Carer Annual Review',
    type: 'assessment',
    client: 'David Parker,Susan Parker',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-20'),
    status: 'active',
    tags: ['annual', 'review'],
    priority: 'medium',
    completeness: 90,
    owner: 'Jennifer Adams',
    lastAccessed: new Date('2023-06-22'),
    compliance: 'complete'
  },
  {
    id: 'DOC-250523-211',
    title: 'Foster Carer Profile',
    type: 'document',
    client: 'Carlos Martinez,Maria Martinez',
    createdAt: new Date('2023-05-25'),
    updatedAt: new Date('2023-05-25'),
    status: 'active',
    tags: ['profile', 'matching'],
    priority: 'medium',
    completeness: 100,
    owner: 'Robert Johnson',
    compliance: 'complete'
  },
  {
    id: 'REP-2023-129',
    title: 'Placement Disruption Report',
    type: 'report',
    client: 'Thomas Wilson,Rachel Wilson',
    createdAt: new Date('2023-07-03'),
    updatedAt: new Date('2023-07-05'),
    status: 'active',
    tags: ['disruption', 'urgent'],
    priority: 'high',
    completeness: 85,
    owner: 'Emily Davis',
    lastAccessed: new Date('2023-07-10'),
    compliance: 'incomplete'
  },
  {
    id: 'DOC-120423-231',
    title: 'Delegated Authority Form',
    type: 'document',
    client: 'William Anderson,Elizabeth Anderson',
    createdAt: new Date('2023-04-12'),
    updatedAt: new Date('2023-04-12'),
    status: 'active',
    tags: ['authority', 'legal'],
    priority: 'medium',
    completeness: 100,
    owner: 'Sarah Wilson',
    compliance: 'complete'
  }
];
