name: Automatic Backup

on:
  # Run this workflow daily at midnight
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper backups

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        
      - name: Build project (if needed)
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Stage and commit any changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automatic backup - $(date +'%Y-%m-%d')"
            git push
          fi 