name: Detect and Backup Changes

on:
  # Run this workflow every hour to detect changes
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Check for file changes
        id: changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Add all changes to see what's modified
          git add -A
          
          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            
            # Commit and push the changes
            git commit -m "Automatic backup - Changes detected $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi 